# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Xu Chi's blog
name: Xu Chi's blog
email: xuchi16@126.com
url: lukathis.github.io
description: > # this means to ignore newlines until "baseurl:"
  A civil engineer who's dreaming to start a brand new career.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://Lukathis.github.io" # the base hostname & protocol for your site
twitter_username: GFW
github_username:  Lukathis
copyright: Xu Chi. All rights reserved.

# Build settings
markdown: kramdown

# Plugins
plugins:
  - jekyll-include-cache

remote_theme: "mmistakes/minimal-mistakes@4.17.1"
